package studio

// This file is the facade completeness gate added in Slice 9 of the package
// restructure (see .tiller/scratch/gosx-studio-restructure-spec-v0.1.md §"Gate
// in CI"). Every exported top-level identifier declared across compat_*.go
// (the deprecated root facade: types, constants, and free functions; methods
// on aliased types are inherited automatically through the alias and need no
// entry here) is referenced below. Referencing every symbol turns "someone
// renamed or deleted a facade alias/wrapper that muddy-noni-commerce,
// pajaritos-forest-school, or gosx-cms/studio still imports" into a LOCAL
// COMPILE FAILURE of this package — caught by `go build ./...` /
// `go test ./...` in gosx-studio's own CI, without needing any of
// the three consumer repos checked out. Without this file, deleting an
// unreferenced exported facade symbol is a silent no-op from
// `go build ./...`'s point of view: Go does not warn about unused
// package-level exported declarations.
//
// The list below is the full alias/wrapper surface of the eight
// compat_<pkg>.go files as of Slice 9: 308 types, 150 consts, 316 funcs (774 total; no
// exported top-level vars in the facade). It was generated by parsing
// compat_*.go with go/parser and listing every exported top-level GenDecl
// (type/const/var) and receiver-less FuncDecl — see the Slice 9 spore for the
// exact scan. Regenerate the same way if a future change to a compat_*.go
// file adds or removes a symbol; until the facade is retired at the end of
// the v0.6.x compatibility window (spec §3/§9), this file should track it
// 1:1.

import "testing"

// --- Types: referenced via zero-value var declarations. A type alias or
// interface/func-type alias cannot be put in a []any slice generically (no
// composite literal for an arbitrary interface/func type), so the compile-
// time reference IS the gate here — there is no companion runtime count. ---
var (
	_ Action
	_ ActionConfig
	_ ActivityPanelOptions
	_ AdvancedFieldPanelOptions
	_ AdvancedPanelOptions
	_ AdvancedPanelSegments
	_ AdvancedSettingsPanelOptions
	_ AdvancedToolsPanelOptions
	_ AppearanceWriter
	_ AuthoringAdapter
	_ AuthoringChange
	_ AuthoringMutation
	_ AuthoringMutationResult
	_ AuthoringOperationKind
	_ AuthoringRefreshFragment
	_ AuthoringSurface
	_ AuthoringValidation
	_ BackendBlogDetailActionStatus
	_ BackendBlogDetailMediaAsset
	_ BackendBlogDetailPageProps
	_ BackendBlogDetailRelation
	_ BackendBlogDetailTag
	_ BackendBlogDetailValues
	_ BackendBlogIndexActionStatus
	_ BackendBlogIndexMediaAsset
	_ BackendBlogIndexPageProps
	_ BackendBlogIndexRelation
	_ BackendBlogIndexTag
	_ BackendBlogIndexValues
	_ BackendCategoryDetailActionStatus
	_ BackendCategoryDetailPageProps
	_ BackendCategoryDetailValues
	_ BackendCategoryIndexActionStatus
	_ BackendCategoryIndexPageProps
	_ BackendCategoryIndexValues
	_ BackendContactActionPaths
	_ BackendContactActions
	_ BackendContactDetailProps
	_ BackendContactMessage
	_ BackendContactReply
	_ BackendContactReplyActionState
	_ BackendContactSubmission
	_ BackendContactTime
	_ BackendDashboardActionState
	_ BackendDashboardAlert
	_ BackendDashboardAuth
	_ BackendDashboardCard
	_ BackendDashboardChecklistItem
	_ BackendDashboardContact
	_ BackendDashboardOrder
	_ BackendDashboardPayment
	_ BackendDashboardProps
	_ BackendDashboardResource
	_ BackendDashboardStat
	_ BackendDashboardTime
	_ BackendDashboardTimelineEvent
	_ BackendDetailPreview
	_ BackendDetailPreviewImage
	_ BackendDetailProps
	_ BackendDetailStatus
	_ BackendDetailTime
	_ BackendEditorActionStatus
	_ BackendEditorMediaAsset
	_ BackendEditorPageProps
	_ BackendEditorPublishPanelStackProps
	_ BackendEditorScripts
	_ BackendEditorWorkbenchContentProps
	_ BackendEditorWorkbenchPanelStackProps
	_ BackendEditorWorkbenchProps
	_ BackendGalleryDetailActionStatus
	_ BackendGalleryDetailImage
	_ BackendGalleryDetailMediaAsset
	_ BackendGalleryDetailPageProps
	_ BackendGalleryDetailValues
	_ BackendGalleryIndexActionStatus
	_ BackendGalleryIndexMediaAsset
	_ BackendGalleryIndexPageProps
	_ BackendGalleryIndexValues
	_ BackendMediaAsset
	_ BackendMediaDetailActionStatus
	_ BackendMediaDetailAsset
	_ BackendMediaDetailPageProps
	_ BackendMediaDetailUsage
	_ BackendMediaDetailVariant
	_ BackendMediaLibraryActionStatus
	_ BackendMediaLibraryPageProps
	_ BackendMediaLibraryProps
	_ BackendMediaLibraryRemoteAssetValues
	_ BackendOrderActionPaths
	_ BackendOrderActions
	_ BackendOrderAuditEvent
	_ BackendOrderDetailProps
	_ BackendOrderFulfillmentOption
	_ BackendOrderItem
	_ BackendOrderNotes
	_ BackendOrderPaymentReferences
	_ BackendOrderSpecRow
	_ BackendOrderSummary
	_ BackendOrderTime
	_ BackendOrderTimelineEvent
	_ BackendOrderWebhookEvent
	_ BackendPageDetailActionStatus
	_ BackendPageDetailMediaAsset
	_ BackendPageDetailPageProps
	_ BackendPageDetailValues
	_ BackendPageIndexActionStatus
	_ BackendPageIndexMediaAsset
	_ BackendPageIndexPageProps
	_ BackendPageIndexValues
	_ BackendProductDetailActionStatus
	_ BackendProductDetailCategory
	_ BackendProductDetailImage
	_ BackendProductDetailMediaAsset
	_ BackendProductDetailPageProps
	_ BackendProductDetailValues
	_ BackendProductIndexActionStatus
	_ BackendProductIndexCategory
	_ BackendProductIndexMediaAsset
	_ BackendProductIndexPageProps
	_ BackendProductIndexValues
	_ BackendResourceCard
	_ BackendResourceIndexProps
	_ BackendResourceLink
	_ BackendResourceTable
	_ BackendResourceTableCell
	_ BackendResourceTableRow
	_ BackendResourceTime
	_ BackendSearchProps
	_ BackendSearchResult
	_ BackendSettingsMediaAsset
	_ BackendSettingsNotifications
	_ BackendSettingsProps
	_ BackendSettingsShippingOption
	_ BackendSettingsStatus
	_ BackendSettingsValues
	_ BackendStorefrontPreviewProps
	_ BackendStorefrontPreviewRoute
	_ BackendWorkbenchAction
	_ BackendWorkbenchField
	_ BackendWorkbenchProps
	_ BackendWorkbenchResource
	_ BackendWorkbenchTool
	_ BlockLayoutEngineHostOptions
	_ BlockLayoutEngineOptions
	_ BlockLayoutEngineRuntime
	_ BlockLayoutEngineSegments
	_ BlockLibraryPanelOptions
	_ BlockSummary
	_ Boundary
	_ BrandMediaPickerAssetItem
	_ BrandMediaPickerOptions
	_ BrandMediaPickerProps
	_ BrandPanelOptions
	_ BrandPanelSegments
	_ CanvasAction
	_ CanvasActionKind
	_ CanvasBlock
	_ CanvasConfig
	_ CanvasPreviewShell
	_ CanvasSurface
	_ CanvasViewport
	_ CanvasWorkspace
	_ CanvasZoomLevel
	_ CheckoutPanelOptions
	_ Component
	_ ComponentSource
	_ ComponentTemplate
	_ CompositionIntent
	_ CompositionIntentKind
	_ CompositionLibrary
	_ CompositionStep
	_ CompositionWorkspace
	_ ConfigControlOption
	_ ConfigControlSpec
	_ ConfigSection
	_ Control
	_ ControlKind
	_ ControlOption
	_ Engine
	_ EngineCapability
	_ EngineConfig
	_ EngineKind
	_ Feature
	_ Flow
	_ FlowAction
	_ FlowDesignerAction
	_ FlowDesignerCheck
	_ FlowDesignerField
	_ FlowDesignerFlow
	_ FlowDesignerNode
	_ FlowDesignerPanelOptions
	_ FlowDesignerProps
	_ FlowDesignerReadiness
	_ FlowDesignerStep
	_ FlowField
	_ FlowNode
	_ FlowReadinessCheck
	_ FlowStep
	_ HomeInspectorPanelOptions
	_ HomeLayerSelectionItem
	_ HomeLayerSelectionProps
	_ HomeLayersPanelOptions
	_ HomeLayersPanelSegments
	_ HomePageSurfaceInput
	_ HostConfig
	_ HostLabels
	_ InspectorChromePanelOptions
	_ InspectorFieldListOptions
	_ InspectorFieldRowOptions
	_ LookPanelOptions
	_ MediaSummary
	_ Metric
	_ Mode
	_ ModeConfig
	_ Mounter
	_ NavigationPanelOptions
	_ Options
	_ Page
	_ PageArtboardComponent
	_ PageArtboardSurfaceInput
	_ PageBlueprint
	_ PageGroup
	_ PageGroupCount
	_ PageSurfaceTheme
	_ PageThumbnailHero
	_ PageThumbnailInput
	_ PageThumbnailTheme
	_ Panel
	_ PanelConfig
	_ PermissionConfig
	_ Plugin
	_ PluginIsland
	_ PluginRegistry
	_ PreviewSharePanelOptions
	_ PublishPanelOptions
	_ ReadinessStatus
	_ ResourceAdapter
	_ ResourceBinding
	_ ResourceCapability
	_ ResourceConfig
	_ ResourceKind
	_ RevisionHistoryPanelOptions
	_ RevisionSummary
	_ RuntimeConfig
	_ RuntimeContract
	_ RuntimeMethod
	_ RuntimePayloadField
	_ Section
	_ SectionFieldWriter
	_ Shell
	_ ShellConfig
	_ ShellReadiness
	_ ShellReadinessItem
	_ ShellReadinessStatus
	_ SiteMap
	_ SiteMapAuthoringFormsOptions
	_ SiteMapAuthoringPanelsOptions
	_ SiteMapBoardOptions
	_ SiteMapCanvasOptions
	_ SiteMapCanvasSurfaceMode
	_ SiteMapCanvasSurfaceOptions
	_ SiteMapEngineHostOptions
	_ SiteMapEngineOptions
	_ SiteMapEngineRender
	_ SiteMapEngineRuntime
	_ SiteMapEngineSegments
	_ SiteMapNodePosition
	_ SiteMapViewOptions
	_ SiteNavigatorItem
	_ SiteNavigatorPanelOptions
	_ SiteNavigatorProps
	_ Store
	_ StudioEngineHostsOptions
	_ StudioEngineRuntime
	_ StyleControlOption
	_ StyleControlSpec
	_ StyleDraftWriter
	_ StyleOverrides
	_ StyleSection
	_ StyleValueLookup
	_ SurfaceKind
	_ Viewport
	_ WorkbenchCanvasBarOptions
	_ WorkbenchCanvasStatusOptions
	_ WorkbenchCanvasToolsOptions
	_ WorkbenchCommandPaletteOptions
	_ WorkbenchFrameOptions
	_ WorkbenchFrameSegments
	_ WorkbenchHistoryControlsOptions
	_ WorkbenchMetricStripOptions
	_ WorkbenchModebarOptions
	_ WorkbenchRailResizer
	_ WorkbenchRailResizerOptions
	_ WorkbenchSaveStatusOptions
	_ WorkbenchShellSource
	_ WorkbenchShellViewOptions
	_ WorkbenchToolbarOptions
	_ WorkbenchViewportControlsOptions
	_ WorkbenchZoomControlsOptions
	_ WorkbenchZoomLevel
	_ WorkspaceCanvas
	_ WorkspaceLayer
	_ WorkspaceLink
	_ WorkspaceLinkKind
	_ WorkspaceLinkPath
	_ WorkspaceNode
	_ WorkspaceNodeKind
	_ WorkspaceNodePoint
)

// --- Constants and free functions: referenced as values in a slice, which
// gives TestFacadeCompleteness a runtime-checkable count in addition to the
// compile-time gate above. ---
var facadeValueRefs = []any{
	AuthoringFieldBinding,
	AuthoringFieldBreakpoint,
	AuthoringFieldComponentKey,
	AuthoringFieldComponentLabel,
	AuthoringFieldComponentTemplateKey,
	AuthoringFieldControlKey,
	AuthoringFieldControlKind,
	AuthoringFieldIntentKey,
	AuthoringFieldIntentKind,
	AuthoringFieldOperation,
	AuthoringFieldPageBlueprintKey,
	AuthoringFieldPageKey,
	AuthoringFieldPageLabel,
	AuthoringFieldPageRoute,
	AuthoringFieldPosition,
	AuthoringFieldState,
	AuthoringFieldStyleProperty,
	AuthoringFieldStyleValue,
	AuthoringFieldTargetRegion,
	AuthoringFieldValue,
	AuthoringFieldVisible,
	AuthoringOperationApplyIntent,
	AuthoringOperationDeleteComponent,
	AuthoringOperationDuplicateComponent,
	AuthoringOperationReorderComponent,
	AuthoringOperationSaveAppearance,
	AuthoringOperationSaveControl,
	AuthoringOperationSetStyle,
	AuthoringOperationToggleVisibility,
	AuthoringOperationUpdatePage,
	BlockLayoutAddBlockAttr,
	BlockLayoutEngineName,
	BlockLayoutHandleAttr,
	BlockLayoutIndexAttr,
	BlockLayoutMoveAttr,
	BlockLayoutOrderAttr,
	BlockLayoutPillAttr,
	BlockLayoutReorderEvent,
	BlockLayoutRowAttr,
	BlockLayoutSelectEvent,
	BlockLayoutSelectedClass,
	BlockLayoutVisibleAttr,
	Canvas2DPainterPath,
	CanvasActionContent,
	CanvasActionInlineText,
	CanvasActionMoveDown,
	CanvasActionMoveUp,
	CanvasActionReveal,
	CanvasActionStyle,
	CanvasActionToggleVisibility,
	CanvasContextualPanelPath,
	CanvasDefaultInlineInstallerPath,
	CanvasEngineName,
	CanvasInlineEditPath,
	CanvasSelectionBridgePath,
	CanvasWASMFreeClientPath,
	CapabilityDragDrop,
	CapabilityInlineEdit,
	CapabilityPanZoom,
	CapabilityPersistence,
	CapabilityPopout,
	CapabilityPreview,
	CapabilitySelection,
	CommandRuntimePath,
	ComponentSourceCMS,
	ComponentSourceHost,
	ComponentSourcePlugin,
	ComponentSourceStudio,
	CompositionIntentAddComponent,
	CompositionIntentCreatePage,
	ControlChoice,
	ControlColor,
	ControlFlow,
	ControlLink,
	ControlMedia,
	ControlNumber,
	ControlRichText,
	ControlScene3D,
	ControlSource,
	ControlText,
	ControlToggle,
	EngineBlockLayout,
	EngineCanvas,
	EngineFlow,
	EngineRuntimePath,
	EngineScene3D,
	EngineSiteMap,
	FlowDesignerName,
	InspectorFieldRowVariantHome,
	PackageAdmin,
	PackageCMS,
	PackageStudio,
	PageGroupCommerce,
	PageGroupContent,
	PageGroupFlows,
	PageGroupSite,
	PageGroupUtility,
	PreviewSubscriberPath,
	ReadinessBlocked,
	ReadinessReady,
	ReadinessWatch,
	ResourceContacts,
	ResourceExecute,
	ResourceFlows,
	ResourceLifecycle,
	ResourceList,
	ResourceMedia,
	ResourceOrders,
	ResourcePages,
	ResourcePreview,
	ResourceProducts,
	ResourcePublish,
	ResourceRead,
	ResourceRestore,
	ResourceRevisions,
	ResourceSearch,
	ResourceSettings,
	ResourceWrite,
	RuntimeRoot,
	ShellReadinessNext,
	ShellReadinessReady,
	ShellReadinessWatch,
	Showcase3DEngineName,
	SiteMapCanvasSurfaceCanvasDefault,
	SiteMapCanvasSurfaceCoRender,
	SiteMapCanvasSurfaceOff,
	SiteMapCanvasSurfaceWASMFree,
	SiteMapEngineName,
	StateRuntimePath,
	StyleBreakpointBase,
	StyleBreakpointMobile,
	StyleBreakpointTablet,
	StyleStateActive,
	StyleStateDefault,
	StyleStateDisabled,
	StyleStateFocus,
	StyleStateHover,
	StylesheetPath,
	SurfaceCanvas,
	SurfaceFlow,
	SurfaceInspector,
	SurfacePublish,
	SurfaceShowcase3D,
	SurfaceSiteMap,
	WorkbenchRuntimePath,
	WorkspaceLinkBinds,
	WorkspaceLinkContains,
	WorkspaceNodeComponent,
	WorkspaceNodePage,
	WorkspaceNodeResource,
	ApplySaveAppearance,
	ApplySaveSectionField,
	ApplySetStyle,
	AssetHandler,
	AssetHref,
	AuthoringActionHandler,
	AuthoringFieldNamesView,
	AuthoringMutationForComponentDelete,
	AuthoringMutationForComponentDuplicate,
	AuthoringMutationForComponentReorder,
	AuthoringMutationForComponentVisibility,
	AuthoringMutationForControl,
	AuthoringMutationForPage,
	AuthoringMutationForStyle,
	AuthoringMutationFormInputViews,
	AuthoringMutationFromForm,
	AuthoringMutationFromIntent,
	AuthoringMutationResultView,
	AuthoringMutationView,
	AuthoringRefreshFragments,
	AuthoringRuntimeScript,
	AuthoringSiteMapView,
	AuthoringSurfaceView,
	BlockLayoutEngineHostFromMap,
	BoolAttr,
	BuildCustomCSSView,
	BuildSectionConfigView,
	BuildStyleControlView,
	Canvas2DPainterHandler,
	Canvas2DPainterScript,
	CanvasActionKindLabel,
	CanvasContextualPanelHandler,
	CanvasContextualPanelScript,
	CanvasDefaultInlineInstallerHandler,
	CanvasDefaultInlineInstallerScript,
	CanvasInlineEditHandler,
	CanvasInlineEditScript,
	CanvasPreviewShellView,
	CanvasSelectionBridgeHandler,
	CanvasSelectionBridgeScript,
	CanvasWASMFreeClientHandler,
	CanvasWASMFreeClientScript,
	CommandRuntimeHandler,
	CommandRuntimeScript,
	ComponentSourceLabel,
	ControlKindLabel,
	DefaultBoundary,
	DefaultCanvasActions,
	DefaultCanvasPreviewShell,
	DefaultEngines,
	DefaultFeatures,
	DefaultResourceAdapters,
	DefaultRuntimeConfig,
	DefaultRuntimeContracts,
	DefaultShellConfig,
	EngineHostView,
	EngineRuntimeHandler,
	EngineRuntimeHandlerWithPlugins,
	EngineRuntimeScript,
	EngineRuntimeScriptWithPlugins,
	FeatureFlagAttrs,
	FirstNonEmpty,
	FmtAny,
	HomeLayerSelectionPropsFromMap,
	HostShell,
	IsSupportedStyleProperty,
	LinkAction,
	MountRuntimes,
	New,
	NewMetric,
	NewMode,
	NewPanel,
	NewPluginRegistry,
	NewSection,
	NewShellReadiness,
	NewShellReadinessItem,
	NewViewport,
	NoCodeAuthoringSurface,
	NormalizeKey,
	NormalizeMetrics,
	NormalizeModes,
	NormalizeShellReadiness,
	NormalizeShellReadinessStatus,
	NormalizeViewports,
	PageGroupLabel,
	PageThumbnailDataURI,
	ParseSectionFieldBinding,
	PreviewSubscriberHandler,
	PreviewSubscriberScript,
	PrimaryAction,
	ReadinessStatusLabel,
	Render,
	RenderActivityPanel,
	RenderAdvancedFieldPanel,
	RenderAdvancedPanel,
	RenderAdvancedPanelSegments,
	RenderAdvancedSettingsPanel,
	RenderAdvancedToolsPanel,
	RenderBackendBlogCreatePanel,
	RenderBackendBlogDetailContent,
	RenderBackendBlogDetailForm,
	RenderBackendBlogDetailMediaDatalist,
	RenderBackendBlogDetailPage,
	RenderBackendBlogDetailScripts,
	RenderBackendBlogDetailTagsDatalist,
	RenderBackendBlogIndexContent,
	RenderBackendBlogIndexMediaDatalist,
	RenderBackendBlogIndexPage,
	RenderBackendBlogIndexScripts,
	RenderBackendBlogIndexTagsDatalist,
	RenderBackendCategoryCreatePanel,
	RenderBackendCategoryDetailContent,
	RenderBackendCategoryDetailForm,
	RenderBackendCategoryDetailPage,
	RenderBackendCategoryIndexContent,
	RenderBackendCategoryIndexPage,
	RenderBackendContactDetail,
	RenderBackendContactDetailContent,
	RenderBackendContactDetailHeading,
	RenderBackendContactDetailPage,
	RenderBackendContactDetailPageContent,
	RenderBackendContactMessage,
	RenderBackendContactReplyForm,
	RenderBackendContactReplyHistory,
	RenderBackendContactStatusForm,
	RenderBackendContactSubmission,
	RenderBackendDashboard,
	RenderBackendDetail,
	RenderBackendDetailContent,
	RenderBackendDetailHeading,
	RenderBackendDetailPreview,
	RenderBackendEditorBoard,
	RenderBackendEditorLeftRail,
	RenderBackendEditorMediaDatalist,
	RenderBackendEditorPage,
	RenderBackendEditorPublishPanelStack,
	RenderBackendEditorRightRail,
	RenderBackendEditorRuntimeScripts,
	RenderBackendEditorStatuses,
	RenderBackendEditorWorkbench,
	RenderBackendEditorWorkbenchCanvasBar,
	RenderBackendEditorWorkbenchCanvasStatus,
	RenderBackendEditorWorkbenchCanvasTools,
	RenderBackendEditorWorkbenchContent,
	RenderBackendEditorWorkbenchPanelStack,
	RenderBackendEditorWorkbenchToolbar,
	RenderBackendEditorWorkbenchViewportControls,
	RenderBackendEditorWorkbenchZoomControls,
	RenderBackendGalleryCreatePanel,
	RenderBackendGalleryDetailContent,
	RenderBackendGalleryDetailForm,
	RenderBackendGalleryDetailMediaDatalist,
	RenderBackendGalleryDetailPage,
	RenderBackendGalleryDetailScripts,
	RenderBackendGalleryIndexContent,
	RenderBackendGalleryIndexMediaDatalist,
	RenderBackendGalleryIndexPage,
	RenderBackendGalleryIndexScripts,
	RenderBackendMediaDetailContent,
	RenderBackendMediaDetailForm,
	RenderBackendMediaDetailPage,
	RenderBackendMediaLibrary,
	RenderBackendMediaLibraryActions,
	RenderBackendMediaLibraryAssets,
	RenderBackendMediaLibraryContent,
	RenderBackendMediaLibraryHeading,
	RenderBackendMediaLibraryPage,
	RenderBackendMediaLibraryPageContent,
	RenderBackendMediaLibraryRemoteAssetForm,
	RenderBackendMediaLibraryUploadForm,
	RenderBackendMediaReplaceForm,
	RenderBackendOrderDetail,
	RenderBackendOrderDetailActions,
	RenderBackendOrderDetailAudit,
	RenderBackendOrderDetailContent,
	RenderBackendOrderDetailHeading,
	RenderBackendOrderDetailItems,
	RenderBackendOrderDetailNotes,
	RenderBackendOrderDetailPage,
	RenderBackendOrderDetailPageContent,
	RenderBackendOrderDetailPaymentReferences,
	RenderBackendOrderDetailShippingAddress,
	RenderBackendOrderDetailSummary,
	RenderBackendOrderDetailTimeline,
	RenderBackendOrderDetailWebhooks,
	RenderBackendPageCreatePanel,
	RenderBackendPageDetailContent,
	RenderBackendPageDetailForm,
	RenderBackendPageDetailMediaDatalist,
	RenderBackendPageDetailPage,
	RenderBackendPageDetailScripts,
	RenderBackendPageIndexContent,
	RenderBackendPageIndexMediaDatalist,
	RenderBackendPageIndexPage,
	RenderBackendPageIndexScripts,
	RenderBackendProductCreatePanel,
	RenderBackendProductDetailContent,
	RenderBackendProductDetailForm,
	RenderBackendProductDetailMediaDatalist,
	RenderBackendProductDetailPage,
	RenderBackendProductDetailScripts,
	RenderBackendProductIndexContent,
	RenderBackendProductIndexMediaDatalist,
	RenderBackendProductIndexPage,
	RenderBackendProductIndexScripts,
	RenderBackendResourceIndex,
	RenderBackendResourceIndexContent,
	RenderBackendSearch,
	RenderBackendSearchContent,
	RenderBackendSearchForm,
	RenderBackendSearchHeading,
	RenderBackendSearchResults,
	RenderBackendSettingsContent,
	RenderBackendSettingsForm,
	RenderBackendSettingsHeading,
	RenderBackendSettingsMediaDatalist,
	RenderBackendSettingsPage,
	RenderBackendSettingsScripts,
	RenderBackendStorefrontPreview,
	RenderBackendStorefrontPreviewContent,
	RenderBackendStorefrontPreviewHeading,
	RenderBackendStorefrontPreviewPanel,
	RenderBackendWorkbench,
	RenderBackendWorkbenchContent,
	RenderBackendWorkbenchHeading,
	RenderBackendWorkbenchResources,
	RenderBackendWorkbenchTools,
	RenderBlockLayoutEngine,
	RenderBlockLayoutEngineHost,
	RenderBlockLayoutEngineSegments,
	RenderBlockLibraryPanel,
	RenderBrandMediaPicker,
	RenderBrandPanel,
	RenderBrandPanelSegments,
	RenderCheckoutPanel,
	RenderComponentStylesCSS,
	RenderFlowDesignerActions,
	RenderFlowDesignerGraph,
	RenderFlowDesignerHeader,
	RenderFlowDesignerPanel,
	RenderFlowDesignerReadiness,
	RenderFlowDesignerRoute,
	RenderHomeInspectorPanel,
	RenderHomeLayerSelection,
	RenderHomeLayersPanel,
	RenderHomeLayersPanelSegments,
	RenderHomePageSurfaceMarkup,
	RenderInspectorChromePanel,
	RenderInspectorControl,
	RenderInspectorFieldList,
	RenderInspectorFieldRow,
	RenderLookPanel,
	RenderNavigationPanel,
	RenderPageArtboardSurfaceMarkup,
	RenderPreviewSharePanel,
	RenderPublishPanel,
	RenderRevisionHistoryPanel,
	RenderSiteMapAuthoringForms,
	RenderSiteMapAuthoringPanels,
	RenderSiteMapBoard,
	RenderSiteMapCanvasEngine,
	RenderSiteMapCanvasSurface,
	RenderSiteMapEngine,
	RenderSiteMapEngineSegments,
	RenderSiteNavigatorHeader,
	RenderSiteNavigatorList,
	RenderSiteNavigatorPanel,
	RenderStudioEngineHosts,
	RenderStylePanel,
	RenderWorkbenchCanvasBar,
	RenderWorkbenchCanvasStatus,
	RenderWorkbenchCanvasTools,
	RenderWorkbenchCommandPalette,
	RenderWorkbenchFrame,
	RenderWorkbenchFrameSegments,
	RenderWorkbenchHistoryControls,
	RenderWorkbenchMetricStrip,
	RenderWorkbenchModebar,
	RenderWorkbenchPreviewDockShell,
	RenderWorkbenchRailResizer,
	RenderWorkbenchSaveStatus,
	RenderWorkbenchToolbar,
	RenderWorkbenchViewportControls,
	RenderWorkbenchZoomControls,
	ResourceAdapterByKind,
	ResourceKindLabel,
	RuntimeAssetModTime,
	RuntimeContractByGlobal,
	ScriptHandler,
	SectionFieldBinding,
	ShellReadinessActionLabel,
	ShellReadinessStatusLabel,
	ShellReadinessView,
	SiteMapAuthoringView,
	SiteMapEngineHostFromMap,
	SiteMapRuntimeScript,
	SiteNavigatorPropsFromMap,
	StateRuntimeHandler,
	StateRuntimeScript,
	StudioAttrView,
	StyleFormIDPart,
	Stylesheet,
	StylesheetHandler,
	SupportedStyleBreakpoints,
	SupportedStyleProperties,
	SupportedStyleStates,
	View,
	WorkbenchRailResizerView,
	WorkbenchRuntimeHandler,
	WorkbenchRuntimeScript,
	WorkbenchShellSourceFromShell,
	WorkbenchShellView,
	WorkbenchShellViewForShell,
	WorkbenchZoomLevelViews,
	WorkspaceLinkKindLabel,
	WorkspaceNodeKindLabel,
}

const wantFacadeValueRefCount = 466 // 150 consts + 316 funcs

func TestFacadeCompleteness(t *testing.T) {
	if got := len(facadeValueRefs); got != wantFacadeValueRefCount {
		t.Fatalf("facadeValueRefs count drifted: got %d want %d (const+func facade surface); "+
			"if this is an intentional facade change, regenerate this file per its header comment", got, wantFacadeValueRefCount)
	}
}
