;(function(){
  "use strict";
  if(typeof window==="undefined"||typeof document==="undefined")return;
  var installed=new WeakSet();
  function id(v){return typeof v==="string"&&/^[A-Za-z0-9_.-]{1,128}$/.test(v)?document.getElementById(v):null}
  function safeNav(v){return typeof v==="string"&&(/^\/(?!\/)[^\\\r\n]*$/.test(v)||/^https:\/\/[^\s]+$/.test(v)||/^mailto:[^\s@]+@[^\s@]+$/.test(v))}
  function reduced(){return !!(window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)}
  function allowed(g){return (g.conditions||[]).every(function(c){if(c.kind==="always")return true;if(c.kind==="reduced-motion")return reduced();if(c.kind==="no-reduced-motion")return !reduced();if(c.kind==="viewport-min"){var w=window.innerWidth||0;return c.value==="mobile"||c.value==="tablet"&&w>=768||c.value==="desktop"&&w>=1024}return false})}
  function action(a){var el=id(a.targetId);switch(a.kind){case"show":if(el){el.hidden=false;el.setAttribute("aria-hidden","false")}break;case"hide":if(el){el.hidden=true;el.setAttribute("aria-hidden","true")}break;case"toggle-class":if(el&&/^[A-Za-z0-9_.-]{1,128}$/.test(a.value)&&a.value.indexOf("js-")!==0)el.classList.toggle(a.value);break;case"navigate":if(safeNav(a.value))window.location.assign(a.value);break;case"scroll":if(el)el.scrollIntoView({behavior:reduced()?"auto":"smooth",block:"start"});break;case"focus":if(el&&typeof el.focus==="function")el.focus({preventScroll:true});break;case"set-variant":if(el)el.setAttribute("data-variant",a.value);break;case"play-media":if(el&&typeof el.play==="function")el.play().catch(function(){});break;case"pause-media":if(el&&typeof el.pause==="function")el.pause();break}}
  function run(g){if(!allowed(g))return;var chain=Promise.resolve();(g.actions||[]).forEach(function(a){chain=chain.then(function(){return new Promise(function(done){var delay=reduced()?0:Math.max(0,Math.min(60000,a.delayMs||0));window.setTimeout(function(){action(a);done()},delay)})})})}
  function bind(el,g){if(!g||g.enabled===false)return;var fire=function(){run(g)};if(g.event==="click"){el.addEventListener("click",fire);if(!/^(A|BUTTON|INPUT|SELECT|TEXTAREA)$/.test(el.tagName)){if(!el.hasAttribute("tabindex"))el.tabIndex=0;el.setAttribute("role","button");el.addEventListener("keydown",function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();fire()}})}}else if(g.event==="submit")el.addEventListener("submit",fire);else if(g.event==="focus")el.addEventListener("focusin",fire);else if(g.event==="hover"){el.addEventListener("mouseenter",fire);el.addEventListener("focusin",fire)}else if(g.event==="viewport-enter"){if("IntersectionObserver"in window){var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){fire();io.disconnect()}})},{threshold:.1});io.observe(el)}}}
  function install(root){root=root||document;if(installed.has(root))return;installed.add(root);root.querySelectorAll("[data-gosx-interactions]").forEach(function(el){var graphs;try{graphs=JSON.parse(el.getAttribute("data-gosx-interactions")||"[]")}catch(_){graphs=[]}(Array.isArray(graphs)?graphs:[]).forEach(function(g){bind(el,g)})})}
  window.GoSXStudioInteractions={install:install};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){install(document)},{once:true});else install(document);
})();
