import { test, expect } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
const runtime=fs.readFileSync(path.join(__dirname,"..","flowruntime","runtime.js"),"utf8");
const graph={id:"signup",name:"Signup",initialStepId:"form",steps:[{id:"form",kind:"form"},{id:"done",kind:"success"},{id:"error",kind:"error"}],transitions:[{id:"ok",fromStepId:"form",toStepId:"done",kind:"success"},{id:"bad",fromStepId:"form",toStepId:"error",kind:"error"}]};
function markup(extra=""){return `<div ${extra} data-gosx-flow='${JSON.stringify(graph)}'><div data-flow-announcer role="status" aria-live="polite"></div><section data-flow-step="form"><form data-flow-form novalidate><label>Email<input data-flow-field name="email" type="email" required></label><button>Complete</button></form></section><section data-flow-step="done"><button data-flow-autofocus>Success</button></section><section data-flow-step="error"><button data-flow-autofocus>Error</button></section></div>`}
test("keyboard completion and validation error branch are accessible",async({page})=>{await page.setContent(markup());await page.addScriptTag({content:runtime});await page.locator("input").fill("bad");await page.locator("button",{hasText:"Complete"}).press("Enter");await expect(page.locator('[data-flow-step="error"]')).toBeVisible();await expect(page.locator('[data-flow-step="error"] button')).toBeFocused();await expect(page.locator('[data-flow-announcer]')).toContainText("correct");await page.reload();await page.setContent(markup());await page.addScriptTag({content:runtime});await page.locator("input").fill("a@example.com");await page.locator("button",{hasText:"Complete"}).press("Enter");await expect(page.locator('[data-flow-step="done"]')).toBeVisible();await expect(page.locator('[data-flow-step="done"] button')).toBeFocused()});
test("preview cannot bind authoritative canvas",async({page})=>{await page.setContent(`<div data-gosx-flow-preview-scope><main data-authoritative-page-canvas>${markup('data-gosx-flow-preview')}</main><aside>${markup('data-gosx-flow-preview')}</aside></div>`);await page.addScriptTag({content:runtime});let roots=page.locator("[data-gosx-flow]");await expect(roots.nth(0)).not.toHaveAttribute("data-flow-current-step");await expect(roots.nth(1)).toHaveAttribute("data-flow-current-step","form")});
test("unsafe navigation is inert, reduced motion and responsive layouts are safe",async({page})=>{await page.emulateMedia({reducedMotion:"reduce"});let unsafe={...graph,transitions:[{id:"next",fromStepId:"form",toStepId:"done",kind:"success",navigation:"page",destination:"javascript:alert(1)"}]};await page.setContent(markup().replace(JSON.stringify(graph),JSON.stringify(unsafe)));await page.addScriptTag({content:runtime});await page.locator("input").fill("a@example.com");await page.locator("button",{hasText:"Complete"}).press("Enter");await expect(page).toHaveURL("about:blank");for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:800});let d=await page.evaluate(()=>({s:document.documentElement.scrollWidth,c:document.documentElement.clientWidth}));expect(d.s).toBeLessThanOrEqual(d.c+1)}});
